@extends('layouts.app')

@section('pageTitle', 'Dashboard')

@section('content')
<div class="container searchPage-Container">

    <div class="pageTitle-container" id="">
        <h1 class="movieList-pageTitle">Search Movie</h1>
        <hr class="separator-movieList-nowPlaying">
    </div>


    {{-- Search by Title --}}
    <div class="searchPage-searchByTitleContainer">

        <div class="searchPage-searchByTitle-inputGroupContainer">
            <i class="searchPage-searchByTitle-searchIcon icon-magnifier"></i>
            <input class="searchPage-searchByTitle-inputField" id="movie_search" autofocus/>
        </div>
    </div>



    <div class="searchPage-searchByLocationContainer">
        <div class="searchPage-searchByLocation-title">by Location</div>
        <div class="searchPage-searchByLocation-inputGroupContainer">

        </div>
    </div>


        {{--<label for="location_search">Search by location: </label>--}}
        {{--<input id="location_search"/>--}}
        {{--<button id="location_search_button">Search</button>--}}


    <div class="result_list-container">
        <div id="result_list">

        </div>

    </div>


</div>

    <script>
        // Read the arrays in as strings
        var movies_json = "{{ $movies }}";
        var locations_json = "{{ $locations }}";

        // Replace the &quot; literal characters generated by PHP and parse the JSON
        var movies = JSON.parse(movies_json.replace(/(&quot;)/g,"\""));
        var locations = JSON.parse(locations_json.replace(/(&quot;)/g,"\""));

        // Setup the autocomplete fields
        var movie_options = {
            data: movies,

            // Ensure that we find matches only when autofilling
            list: {
                match: {
                    enabled: true
                },
                onChooseEvent: function() {
                    $.ajax({
                        type: "GET",
                        url: "{{ url('sessions/by_movie') }}",
                        data: {
                            title: $("#movie_search").val()
                        },
                        success: function(result) {

                            $movie = result.movie;
                            $releaseDate = intToDate($movie.release_date);


                            $("#result_list").empty();

                            appendMovie($movie);
                            appendSessions(result.sessions);
                            appendSessionList(result.sessions);

                        }
                    })
                }
            },
            theme: "",
            cssClasses: "searchPage-searchByTitle-autoComplete",
            placeholder: "Search by Movie Title"
        };


        // Attach the autocomplete to the input fields
        $("#movie_search").easyAutocomplete(movie_options);


        populateLocationButtons(locations);


        function populateLocationButtons(locations) {

            $.each(locations, function(k, v){
                $('.searchPage-searchByLocation-inputGroupContainer').append(
                        "<div class='searchPage-searchByLocation-locationButton'>"
                                + v
                        +"</div>"
                );
            })
        }

    </script>

    <script>

        // Example of the AJAX call to get sessions by location
        $(document).ready(function() {
            $("#location_search_button").click(function(e) {
                e.preventDefault();

                $.ajax({
                    type: "GET",
                    url: "{{ url('sessions/by_location') }}",
                    data: {
                        name: $("#location_search").val()
                    },
                    success: function(result) {
                        $("#result_list").empty();

                        $.each(result.sessions, function(k, v) {
                            $("#result_list").append('<li>' + v.movie.title + ', Theater ' + v.theater + ' at ' + v.time + '</li>');
                        })
                    }
                })
            })
        });



        $(document).ready(function(){
            $('.easy-autocomplete').removeAttr('style');
            $('.easy-autocomplete input').removeAttr('style');
        });


    </script>

<script type="text/javascript" src="{{ URL::asset('js/search.js') }}"></script>
@endsection