@extends('layouts.app')

@section('pageTitle', 'Dashboard')

@section('content')
<div class="container searchPage-Container">

    <div class="pageTitle-container" id="">
        <h1 class="movieList-pageTitle">Search Movie</h1>
        <hr class="separator-movieList-nowPlaying">
    </div>


    {{-- Search by Title --}}
    <div class="searchPage-searchByTitleContainer">

        <div class="searchPage-searchByTitle-inputGroupContainer">
            <i class="searchPage-searchByTitle-searchIcon icon-magnifier"></i>
            <input class="searchPage-searchByTitle-inputField" id="movie_search" name="movie_search" autofocus/>
        </div>
    </div>



    <div class="searchPage-searchByLocationContainer">
        <div class="searchPage-searchByLocation-title">by Location</div>
        <div class="searchPage-searchByLocation-inputGroupContainer">

        </div>
    </div>


        {{--<label for="location_search">Search by location: </label>--}}
        {{--<input id="location_search"/>--}}
        {{--<button id="location_search_button">Search</button>--}}


    <div class="result_list-container">
        <div id="result_list">

        </div>

    </div>


</div>

    <script>
        // Read the arrays in as strings
        var movies_json = "{{ $movies }}";
        var locations_json = "{{ $locations }}";

        // Replace the &quot; literal characters generated by PHP and parse the JSON
        var movies = JSON.parse(movies_json.replace(/(&quot;)/g,"\""));
        var locations = JSON.parse(locations_json.replace(/(&quot;)/g,"\""));

        // Setup the autocomplete fields
        var movie_options = {
            data: movies,

            // Ensure that we find matches only when autofilling
            list: {
                match: {
                    enabled: true
                },
                onChooseEvent: function() {
                    $.ajax({
                        type: "GET",
                        url: "{{ url('sessions/by_movie') }}",
                        data: {
                            title: $("#movie_search").val()
                        },
                        success: function(result) {
                            $('.searchPage-searchByLocation-locationButton').removeAttr('style');

                            $movie = result.movie;
                            $releaseDate = intToDate($movie.release_date);


                            $("#result_list").empty();

                            appendMovie($movie);
                            appendSessions(result.sessions);
                            appendSessionList(result.sessions);

                        }
                    })
                }
            },
            theme: "",
            cssClasses: "searchPage-searchByTitle-autoComplete",
            placeholder: "Search by Movie Title"
        };


        // Attach the autocomplete to the input fields
        $("#movie_search").easyAutocomplete(movie_options);

        // Loads in all cinema locations to Location Search section
        populateLocationButtons(locations);


        function populateLocationButtons(locations) {

            $.each(locations, function(k, v){
                $('.searchPage-searchByLocation-inputGroupContainer').append(
                        "<div class='searchPage-searchByLocation-locationButton'>"
                                + v
                        +"</div>"
                );
            })
        }

    </script>

    <script>
//        Search by Location
        $('.searchPage-searchByLocation-locationButton').click(function(e){
            $('.searchPage-searchByTitle-inputField').val('');
            $('.searchPage-searchByLocation-locationButton').removeAttr('style');

            $(this).css({
                'transform' : 'scale(1.05)',
                'background' : '#D8C39D',
                'box-shadow' : '0px 0px 50px 25px rgba(0,0,0,0.8)',
                'z-index' : '10',
                'color' : 'black',
            });
            $text = $(this).html();

            $.ajax({
                type: "GET",
                url: "{{ url('sessions/by_location_grouped') }}",
                data: {
                    name: $text
                },
                success: function(result) {
                    $("#result_list").empty();


                    $.each(result.data, function(k, v) {

                        $movie = v.movie;
                        $releaseDate = intToDate($movie.release_date);

                        appendMovieBySession(v);
                    })
                },
                error: function(result) {
                    $("#result_list").empty();
                    console.log(result);
                }
            });

        });




        $(document).ready(function(){
            $('.easy-autocomplete').removeAttr('style');
            $('.easy-autocomplete input').removeAttr('style');
        });


    </script>

<script type="text/javascript" src="{{ URL::asset('js/search.js') }}"></script>
@endsection